package tools

import (
	"context"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// normalizeToolSchemas is server middleware that rewrites the input schema each
// tool advertises so that every parameter uses a plain type instead of a
// ["null", <type>] union.
//
// The MCP input schemas for our tools are generated by reflection via
// github.com/google/jsonschema-go (through the SDK's mcp.AddTool). By default
// that library emits a union type for every slice and pointer field: an
// []string parameter becomes {"type": ["null", "array"], "items": ...} and a
// *string becomes {"type": ["null", "string"]}.
//
// Several MCP clients mis-serialize arguments whose schema declares such a
// "null | <type>" union: the value is dropped and the JSON payload is truncated
// at the key, producing "JSON Parse error: Unexpected EOF" on the server. This
// hits array params -- create_scope (allowlist/denylist), get_request
// (ids/include), delete_findings (ids) -- AND scalar pointer params such as
// run_workflow (request_id/input) and send_request (tls/includeBody). Observed
// in the wild: run_workflow truncates at "input" because *string advertises as
// ["null", "string"].
//
// Applying the fix here -- on the outgoing tools/list result -- keeps it in one
// place instead of at every mcp.AddTool call site, and only touches what the
// client sees. The schema the server validates arguments against is resolved
// separately at registration and is left untouched, so a client that still
// sends an explicit null for an optional param is accepted as before.
//
// schema_nullunion_test.go guards against a regression here.
func normalizeToolSchemas() mcp.Middleware {
	return func(next mcp.MethodHandler) mcp.MethodHandler {
		return func(ctx context.Context, method string, req mcp.Request) (mcp.Result, error) {
			result, err := next(ctx, method, req)
			if err != nil || method != "tools/list" {
				return result, err
			}
			list, ok := result.(*mcp.ListToolsResult)
			if !ok {
				return result, err
			}
			// The result shares the server's stored *Tool pointers, so copy
			// each tool (and clone its schema) before mutating -- never touch
			// the shared state that concurrent list calls also read.
			for i, tool := range list.Tools {
				schema, ok := tool.InputSchema.(*jsonschema.Schema)
				if !ok || schema == nil {
					continue
				}
				cloned := schema.CloneSchemas()
				stripNullUnions(cloned)
				toolCopy := *tool
				toolCopy.InputSchema = cloned
				list.Tools[i] = &toolCopy
			}
			return result, err
		}
	}
}

// stripNullUnions collapses a ["null", <type>] union to that single plain type,
// recursively across the whole schema tree (nested object properties, array
// items, pointer fields, $defs, and the *Of combinators). It applies to every
// type -- container and scalar alike -- because the client truncation bug is
// triggered by the null union regardless of the other member.
func stripNullUnions(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if len(s.Types) > 0 {
		hasNull := false
		nonNull := make([]string, 0, len(s.Types))
		for _, t := range s.Types {
			if t == "null" {
				hasNull = true
				continue
			}
			nonNull = append(nonNull, t)
		}
		if hasNull && len(nonNull) == 1 {
			s.Type = nonNull[0]
			s.Types = nil
		}
	}
	stripNullUnions(s.Items)
	stripNullUnions(s.AdditionalProperties)
	for _, p := range s.Properties {
		stripNullUnions(p)
	}
	for _, p := range s.PrefixItems {
		stripNullUnions(p)
	}
	for _, group := range [][]*jsonschema.Schema{s.AnyOf, s.OneOf, s.AllOf} {
		for _, p := range group {
			stripNullUnions(p)
		}
	}
	for _, d := range s.Defs {
		stripNullUnions(d)
	}
}
